server:
  servlet:
    context-path: '/guide-survie'
  port: 8086

spring:
  application:
    name: 'guide-survie-springboot'

books:
  max-books-authorized: 3
  admin:
    send-email-on-delete: false
    email: ""
    name: ""
